In [1]:
from src.data import load_crypto_data
from src.indicators import add_indicators

df = load_crypto_data("BTC-USD", start="2021-01-01")
df = add_indicators(df)

df.head()

[*********************100%***********************]  1 of 1 completed

,Date,Close,High,Low,Open,Volume,return,short_ma,long_ma,high_low,high_close,low_close,true_range,atr
49,2021-02-19,55888.132812,56113.652344,50937.277344,51675.980469,63495496918,0.081431,43928.417578,38461.302812,5176.375000,4433.855469,742.519531,5176.375000,3250.772879
50,2021-02-20,56099.519531,57505.226562,54626.558594,55887.335938,68145460026,0.003782,45077.675586,38995.810156,2878.667969,1617.093750,1261.574219,2878.667969,3262.952009
51,2021-02-21,57539.945312,58330.570312,55672.609375,56068.566406,51897585191,0.025676,46277.814063,39504.063711,2657.960938,2231.050781,426.910156,2657.960938,3297.400391
52,2021-02-22,54207.320312,57533.390625,48967.566406,57532.738281,92052420332,-0.057918,47212.665625,39932.569648,8565.824219,6.554688,8572.378906,8572.378906,3329.169922
53,2021-02-23,48824.425781,54204.929688,45290.589844,54204.929688,106102492824,-0.099302,47780.282422,40269.619883,8914.339844,2.390625,8916.730469,8916.730469,3763.453404

In [2]:
from src.data import load_crypto_data
from src.indicators import add_indicators
from src.strategies import ma_crossover_strategy
from src.backtest import run_backtest

df = load_crypto_data("BTC-USD", start="2021-01-01")
df = add_indicators(df, short_window=20, long_window=50)
df = ma_crossover_strategy(df)
results = run_backtest(df)

results[["Date", "Close", "position", "strategy_return", "equity_curve", "buy_hold_curve"]].tail()

[*********************100%***********************]  1 of 1 completed

,Date,Close,position,strategy_return,equity_curve,buy_hold_curve
1941,2026-04-26,78657.539062,1.0,0.013471,10780.662259,14074.103947
1942,2026-04-27,77366.625000,1.0,-0.016412,10603.731876,13843.122163
1943,2026-04-28,76350.671875,1.0,-0.013132,10464.487149,13661.338827
1944,2026-04-29,75776.132812,1.0,-0.007525,10385.741849,13558.537206
1945,2026-04-30,76409.992188,1.0,0.008365,10472.617486,13671.952943

In [3]:
from src.metrics import calculate_metrics

metrics = calculate_metrics(results)
metrics

{'Total Return': np.float64(0.045398515475614465),
 'Volatility': np.float64(0.3140225368293722),
 'Sharpe Ratio': np.float64(0.17614576279058164),
 'Max Drawdown': -0.594954135026656,
 'Win Rate': 0.24947257383966245,
 'Average Win': np.float64(0.020241055748107892),
 'Average Loss': np.float64(-0.01757744593174328),
 'Profit Factor': np.float64(1.0454440800891478),
 'Expectancy': np.float64(-0.008142766978911208)}

In [4]:
from src.backtest import generate_trade_log

trade_log = generate_trade_log(results)
trade_log.head()

ImportError: cannot import name 'generate_trade_log' from 'src.backtest' (C:\Users\USER\anaconda_projects\f5dceb7c-2e6e-4a9a-aba5-413774516975\src\backtest.py)

In [5]:
import importlib
import src.backtest

importlib.reload(src.backtest)

In [6]:
from src.backtest import generate_trade_log

In [7]:
trade_log = generate_trade_log(results)
trade_log.head()

    Trade Date         Price  Position    Return        Equity
50  2021-02-20  56099.519531       1.0  0.001782  10017.823185
117 2021-04-28  54824.703125       0.0 -0.002000   9807.738423
213 2021-08-02  39201.945312       1.0 -0.021336   9598.481827
266 2021-09-24  42839.750000       0.0 -0.002000  10970.448685
284 2021-10-12  56041.058594       1.0 -0.027115  10672.984971

In [9]:
from src.data import load_crypto_data
from src.indicators import add_indicators
from src.strategies import ma_crossover_strategy
from src.backtest import run_backtest, generate_trade_log
from src.metrics import calculate_metrics

df = load_crypto_data("BTC-USD", start="2021-01-01")
df = add_indicators(df, short_window=20, long_window=50)
df = ma_crossover_strategy(df)

results = run_backtest(
    df,
    initial_capital=10000,
    transaction_cost=0.001,
    slippage=0.001,
    stop_loss_atr=2,
    take_profit_atr=3
)

metrics = calculate_metrics(results)
trade_log = generate_trade_log(results)

metrics, trade_log.head()

[*********************100%***********************]  1 of 1 completed

TypeError: run_backtest() got an unexpected keyword argument 'stop_loss_atr'

In [10]:
import importlib
import src.backtest

importlib.reload(src.backtest)

In [11]:
from src.backtest import run_backtest, generate_trade_log

In [12]:
results = run_backtest(
    df,
    initial_capital=10000,
    transaction_cost=0.001,
    slippage=0.001,
    stop_loss_atr=2,
    take_profit_atr=3
)

In [14]:
from src.data import load_crypto_data
from src.indicators import add_indicators
from src.strategies import ma_crossover_strategy
from src.backtest import run_backtest, generate_trade_log
from src.metrics import calculate_metrics

df = load_crypto_data("BTC-USD", start="2021-01-01")
df = add_indicators(df, short_window=20, long_window=50)
df = ma_crossover_strategy(df)

results = run_backtest(
    df,
    initial_capital=10000,
    transaction_cost=0.001,
    slippage=0.001,
    stop_loss_atr=2,
    take_profit_atr=3
)

metrics = calculate_metrics(results)
trade_log = generate_trade_log(results)

metrics, trade_log.head()

[*********************100%***********************]  1 of 1 completed

({'Total Return': np.float64(-0.14799133291121092),
  'Volatility': np.float64(0.29898621793486635),
  'Sharpe Ratio': np.float64(0.07799178241347392),
  'Max Drawdown': -0.5220929269386146,
  'Win Rate': 0.25355824986821296,
  'Average Win': np.float64(0.019256024974564412),
  'Average Loss': np.float64(-0.017782019113773466),
  'Profit Factor': np.float64(1.0193181188022218),
  'Expectancy': np.float64(-0.008390717476192803)},
     Trade Date         Price  Position    Return        Equity
 50  2021-02-20  56099.519531       1.0  0.001782  10017.823185
 117 2021-04-28  54824.703125       0.0 -0.005787   8565.329584
 213 2021-08-02  39201.945312       1.0 -0.021336   8382.580856
 266 2021-09-24  42839.750000       0.0 -0.047781   8967.350037
 284 2021-10-12  56041.058594       1.0 -0.027115   8724.200342)

In [15]:
metrics

{'Total Return': np.float64(-0.14799133291121092),
 'Volatility': np.float64(0.29898621793486635),
 'Sharpe Ratio': np.float64(0.07799178241347392),
 'Max Drawdown': -0.5220929269386146,
 'Win Rate': 0.25355824986821296,
 'Average Win': np.float64(0.019256024974564412),
 'Average Loss': np.float64(-0.017782019113773466),
 'Profit Factor': np.float64(1.0193181188022218),
 'Expectancy': np.float64(-0.008390717476192803)}

In [16]:
trade_log["exit_reason"].value_counts()

KeyError: 'exit_reason'

In [18]:
import importlib
import src.backtest
importlib.reload(src.backtest)

from src.backtest import run_backtest, generate_trade_log

results = run_backtest(
    df,
    initial_capital=10000,
    transaction_cost=0.001,
    slippage=0.001,
    stop_loss_atr=2,
    take_profit_atr=3
)

trade_log = generate_trade_log(results)
trade_log["Exit Reason"].value_counts()

TypeError: 'NoneType' object is not subscriptable

In [19]:
import importlib
import src.backtest

importlib.reload(src.backtest)

from src.backtest import run_backtest, generate_trade_log

In [20]:
results = run_backtest(
    df,
    initial_capital=10000,
    transaction_cost=0.001,
    slippage=0.001,
    stop_loss_atr=2,
    take_profit_atr=3
)

print(type(results))

<class 'pandas.core.frame.DataFrame'>

In [21]:
trade_log = generate_trade_log(results)
trade_log["Exit Reason"].value_counts()

Exit Reason
Entry          82
Stop Loss      35
Take Profit    28
Signal Exit    22
Name: count, dtype: int64

In [22]:
import importlib
import src.backtest

importlib.reload(src.backtest)

from src.backtest import run_backtest, generate_trade_log
from src.metrics import calculate_metrics

results = run_backtest(
    df,
    initial_capital=10000,
    transaction_cost=0.001,
    slippage=0.001,
    stop_loss_atr=2,
    take_profit_atr=3,
    risk_per_trade=0.01
)

metrics = calculate_metrics(results)
trade_log = generate_trade_log(results)

metrics, trade_log.head()

({'Total Return': np.float64(-0.2116858845839864),
  'Volatility': np.float64(0.0393871871401631),
  'Sharpe Ratio': np.float64(-0.7824915739060315),
  'Max Drawdown': -0.2205458554945915,
  'Win Rate': 0.24196099103848182,
  'Average Win': np.float64(0.0024353393869284003),
  'Average Loss': np.float64(-0.00253251024218585),
  'Profit Factor': np.float64(0.8281209253939431),
  'Expectancy': np.float64(-0.0013304844225952117)},
    Trade Date         Price  Position    Return       Equity   Entry Price  \
 50 2021-02-20  56099.519531       1.0 -0.001676  9983.239194  56099.519531
 52 2021-02-22  54207.320312       1.0 -0.014176  9863.472716  56099.519531
 53 2021-02-23  48824.425781       1.0 -0.009152  9773.206790  48824.425781
 71 2021-03-13  61243.085938       1.0  0.001682  9901.316563  48824.425781
 72 2021-03-14  59302.316406       1.0 -0.004907  9852.727352  59302.316406

        Stop Loss   Take Profit  Exit Reason  Position Size
 50  49573.615513  65888.375558        Entry       0.015324
 52  49573.615513  65888.375558    Stop Loss       0.015324
 53  41297.518973  60114.785993        Entry       0.013104
 71  41297.518973  60114.785993  Take Profit       0.013104
 72  52626.922991  69315.406529        Entry       0.014833  )

In [23]:
from src.regime import add_market_regime

df = load_crypto_data("BTC-USD", start="2021-01-01")
df = add_indicators(df, short_window=20, long_window=50)
df = add_market_regime(df)
df = ma_crossover_strategy(df)

results = run_backtest(
    df,
    initial_capital=10000,
    transaction_cost=0.001,
    slippage=0.001,
    stop_loss_atr=2,
    take_profit_atr=3,
    risk_per_trade=0.01
)

results[["Date", "Close", "trend_regime", "volatility_regime", "strategy_return"]].head()

[*********************100%***********************]  1 of 1 completed

          Date         Close trend_regime volatility_regime  strategy_return
98  2021-04-09  58245.003906      Bullish   High Volatility         0.000000
99  2021-04-10  59793.234375      Bullish   High Volatility         0.001630
100 2021-04-11  60204.964844      Bullish   High Volatility         0.000964
101 2021-04-12  59893.453125      Bullish   High Volatility        -0.000729
102 2021-04-13  63503.457031      Bullish   High Volatility         0.008449

In [24]:
regime_summary = results.groupby("trend_regime")["strategy_return"].agg(
    total_return=lambda x: (1 + x).prod() - 1,
    avg_return="mean",
    volatility="std",
    count="count"
)

regime_summary

              total_return  avg_return  volatility  count
trend_regime
Bearish          -0.300197   -0.000382    0.001798    931
Bullish           0.153637    0.000160    0.002984    918

In [25]:
vol_regime_summary = results.groupby("volatility_regime")["strategy_return"].agg(
    total_return=lambda x: (1 + x).prod() - 1,
    avg_return="mean",
    volatility="std",
    count="count"
)

vol_regime_summary

                   total_return  avg_return  volatility  count
volatility_regime
High Volatility       -0.086820   -0.000097    0.002447    909
Low Volatility        -0.115926   -0.000128    0.002500    940

In [26]:
from src.portfolio import run_multi_asset

portfolio_results = run_multi_asset(
    ["BTC-USD", "ETH-USD", "SOL-USD"],
    start="2021-01-01"
)

portfolio_results

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,Total Return,Volatility,Sharpe Ratio,Max Drawdown,Win Rate,Average Win,Average Loss,Profit Factor,Expectancy,Asset
0,-0.192665,0.039270,-0.723095,-0.210892,0.235262,0.002480,-0.002528,0.838108,-0.001350,BTC-USD
1,-0.195634,0.041401,-0.695916,-0.223332,0.222282,0.002653,-0.002758,0.837601,-0.001555,ETH-USD
2,-0.246025,0.040004,-0.942009,-0.279646,0.215792,0.002636,-0.002694,0.791814,-0.001544,SOL-USD

In [28]:
from src.optimizer import optimize_ma

opt_results = optimize_ma()
opt_results.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

   short_ma  long_ma    Sharpe    Return     MaxDD
5        20      200 -0.248649 -0.067382 -0.084767
1        10      100 -0.343856 -0.094216 -0.128426
7        30      100 -0.361055 -0.091738 -0.119981
2        10      200 -0.388081 -0.101973 -0.128208
8        30      200 -0.406759 -0.107233 -0.116540